<form action="<?= $this->form['action'] ?>" method="<?= $this->form['method'] ?>" id="<?= $this->form['entity_name'] ?>">
    <?php foreach ($this->form['fields'] as $key => $fields): ?>
        <input type="text" data-propreties='<?= json_encode($fields) ?>'>
    <?php endforeach ?>
        <input type="submit">
</form>

<form action="<?= $this->form['action'] ?>" method="<?= $this->form['method'] ?>" id="<?= $this->form['children']['entity_name'] ?>">
    <?php foreach ($this->form['children']['fields'] as $key => $fields): ?>
        <input type="text" data-propreties='<?= json_encode($fields) ?>'>
    <?php endforeach ?>
        <input type="submit">
</form>
<?php print_r($this->data); ?>