<?php if (isset($this->response['form']) && $this->response['form']) { ?>
    <?php if (isset($this->response['form']['children'])): ?>
        <form onSubmit="if (!confirm('Really remove this <?= ucfirst($this->response['form']['form_name']) ?>?')) {
                    return false;
                }" action="<?= ((isset($this->response['form']['data']) && isset($this->response['form']['data']['id']) && $this->response['form']['data']['id']) ? '/' . $this->response['form']['form_name'] . '/id/' . $this->response['form']['data']['id'] : '/' . $this->response['form']['form_name'] ) . '.form' ?>" method="POST" name="form-<?= $this->response['form']['children']['form_name'] ?>">        
            <input name="method" value="<?= $this->response['form']['method'] ?>" type="hidden">
            <div class="form-group">        
                <label id="label-<?= $this->response['form']['form_name'] ?>" for="input-<?= $this->response['form']['form_name'] ?>"><?= ucfirst($this->response['form']['form_name']) ?>: </label>
                <input id="input-<?= $this->response['form']['form_name'] ?>" name="<?= $this->response['form']['form_name'] ?>_id" type="hidden" value="<?= $this->response['form']['id'] ?>" disabled>            
                <p class="form-control-static"><?= $this->response['form']['id'] ?></p>
            </div>
            <?php foreach ($this->response['form']['children']['fields'] as $key => $fields): ?>
                <div class="form-group">
                    <label id="label-<?= $key ?>" for="input-<?= $key ?>"><?= ucfirst($key) ?>: </label>
                    <input id="input-<?= $key ?>" value="<?= (isset($this->response['form']['data']) && isset($this->response['form']['data'][strtolower($key)])) ? $this->response['form']['data'][strtolower($key)] : null ?>" name="<?= $key ?>" type="text" data-propreties='<?= json_encode($fields) ?>' placeholder="Enter <?= ucfirst($key) ?>">
                </div>
            <?php endforeach ?>
            <button type="submit" class="btn btn-default">Save</button>
        </form>    
        <?php if (isset($this->response['form']['data']) && isset($this->response['form']['data']['id']) && $this->response['form']['data']['id']) { ?>
            <form action="<?= '/' . $this->response['form']['form_name'] . '.html' ?>" method="POST" name="form-<?= $this->response['form']['form_name'] ?>" role="form">
                <input name="method" value="DELETE" type="hidden"> 
                <input value="<?= $this->response['form']['data']['id'] ?>" id="delete-id" name="id" type="hidden">
                <button type="submit" class="btn btn-default">Delete</button>   
            </form>
        <?php } ?>
    <?php elseif (isset($this->response['form']['fields'])): ?>
        <form action="<?= ((isset($this->response['form']['data']) && isset($this->response['form']['data']['id']) && $this->response['form']['data']['id']) ? '/' . $this->response['form']['form_name'] . '/id/' . $this->response['form']['data']['id'] : '/' . $this->response['form']['form_name'] ) . '.form' ?>" method="POST" name="form-<?= $this->response['form']['form_name'] ?>" role="form">
            <input name="method" value="<?= $this->response['form']['method'] ?>" type="hidden">         
            <?php foreach ($this->response['form']['fields'] as $key => $fields): ?>
                <?php if ($key == 'id') { ?>
                    <input value="<?= (isset($this->response['form']['data']) && isset($this->response['form']['data'][strtolower($key)])) ? $this->response['form']['data'][strtolower($key)] : null ?>" id="input-<?= $key ?>" name="<?= $key ?>" type="hidden" data-propreties='<?= json_encode($fields) ?>' placeholder="Enter <?= ucfirst($key) ?>">
                <?php } else { ?>
                    <div class="form-group">
                        <label id="label-<?= $key ?>" for="input-<?= $key ?>"><?= ucfirst($key) ?>: </label>
                        <input value="<?= (isset($this->response['form']['data']) && isset($this->response['form']['data'][strtolower($key)])) ? $this->response['form']['data'][strtolower($key)] : null ?>" id="input-<?= $key ?>" name="<?= $key ?>" type="text" data-propreties='<?= json_encode($fields) ?>' placeholder="Enter <?= ucfirst($key) ?>">
                    </div>
                <?php } ?>
            <?php endforeach ?>        
            <button type="submit" class="btn btn-default">Save</button>        
        </form>
        <?php if (isset($this->response['form']['data']) && isset($this->response['form']['data']['id']) && $this->response['form']['data']['id']) { ?>
            <form onSubmit="if (!confirm('Really remove this <?= ucfirst($this->response['form']['form_name']) ?>?')) {
                                    return false;
                                }" action="<?= '/' . $this->response['form']['form_name'] . '.html' ?>" method="POST" name="form-<?= $this->response['form']['form_name'] ?>" role="form">
                <input name="method" value="DELETE" type="hidden"> 
                <input value="<?= $this->response['form']['data']['id'] ?>" id="delete-id" name="id" type="hidden">
                <button type="submit" class="btn btn-default">Delete</button>   
            </form>
        <?php } ?>
    <?php endif; ?>
<?php } else { ?>
    <pre>
        <?php
        print_r($this->response);
        ?>
    </pre>
<?php } ?>